language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
# command to install dependencies
install:
  - pip install -r requirements.txt -U --index-url https://devpi.net/hpk/dev/ --extra-index-url https://pypi.python.org/simple/
# command to run tests
script: PYTEST_EXECUTABLE=$(which py.test) py.test